--- 
abstract: Module for Taishin Bank Convenient Store Payment Management
author: Chia-liang Kao <clkao@aiink.com>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Business-TW-TSIB-CStorePayment
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Fast: 0
  DateTime: 0
  List::MoreUtils: 0
  Test::More: 0
version: 0.02
